name: plant_store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  go_router: ^17.1.0
  google_fonts: ^8.0.2
  lucide_icons_flutter: ^3.1.10
  supabase_flutter: ^2.12.0
  flutter_bloc: ^9.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
